export const excelMapping: Record<string, string> = {
    "Fecha": "created_at",
    "Nombres y Apellidos completos": "full_name",
    "Número de DNI o Carnet de Extranjería": "dni",
    "¿Cuál es tu correo electrónico?": "email",
    "Edad": "age",
    "Fecha de nacimiento": "birth_date",
    "Sexo": "gender",
    "Género": "gender",
    "¿Cuál es tu Instagram?": "instagram",
    "Grado de instrucción": "education_level",
    "¿En qué región o estado radicas?": "region",
    "¿En qué distrito vives?": "district",
    "¿A qué te dedicas?": "occupation",
    "Ocupación": "job_details",
    "¿Cuál es tu objetivo nutricional?": "nutritional_goal",
    "¿Te has atendido en algún servicio de nutrición?": "previous_nutrition_service",
    "Si tu respuesta fue SÍ, ¿Cómo calificarías esa experiencia?": "previous_experience_rating",
    "Por cuánto tiempo has estado siguiendo el plan de alimentación de tu nutricionista (cuenta el tiempo desde que lo iniciaste hasta la actualidad)": "time_following_plan",
    "Peso (Kg)": "weight_kg",
    "Talla (cm)": "height_cm",
    "  Cintura (cm)\n": "waist_cm",
    "¿Presentas algunas de las siguientes condiciones de salud? Puedes seleccionar varias alternativas.": "health_conditions",
    "¿Tienes antecedentes familiares de alguna enfermedad? Puedes seleccionar varias alternativas.": "family_history",
    "¿Consumes algún medicamento?": "takes_medication",
    "¿Qué tipo de medicamento consumes?": "medication_details",
    "¿Con qué frecuencia consumes el medicamento y en qué horarios?": "medication_frequency",
    "¿Te haz realizado algún examen de laboratorio estos últimos 3 meses?": "recent_lab_tests",
    "¿Cómo es tu actividad diaria?": "activity_level",
    "¿Cuál es tu horario de trabajo? Especificar días y horas": "work_schedule",
    "Actualmente ¿Estás realizando ejercicio?": "does_exercise",
    "¿Desde hace cuánto tiempo realizas ejercicio?": "exercise_duration",
    "¿Qué ejercicios realizas? Puedes marcar más de 1 alternativa.": "exercise_types",
    "Si entrenas ¿Qué días son los que entrenas? Puedes marcar más de una alternativa.": "exercise_days",
    "¿A qué hora entrenas frecuentemente?": "exercise_time",
    "¿Cuentas con algún dispositivo para medir tu gasto de calorías por sesión de entrenamiento?": "has_calorie_tracker",
    "Si cuentas con un dispositivo para medir tu gasto calórico, ¿Cuánto es el gasto calórico que marca en tus entrenamientos? (especificar en los diferentes días de entrenamientos, por ejemplo: En miembro superior gaste 300 Kcal, cuando hago HIIT unas 600 Kca": "calorie_expenditure_details",
    "¿Cómo está actualmente tu apetito?": "appetite_level",
    "Si tienes tu apetito aumentado ¿En qué horario del día lo sientes? Puedes marcar más de una alternativa.": "appetite_peak_time",
    "¿Cómo está actualmente tu sed?": "thirst_level",
    "¿Qué cantidad de agua consumes en el día?": "water_intake",
    "¿Cómo está actualmente tu sueño?": "sleep_quality",
    "¿Cuántas horas duermes usualmente?": "sleep_hours",
    "¿Cómo están tus deposiciones?": "bowel_movements",
    "¿Con qué frecuencia realizas deposiciones?": "bowel_frequency",
    "¿Cómo está tu orina?": "urine_status",
    "Indica que número coincide con el color de tu orina. Para este proceso tienes que ver la orina en un recipiente transparente de plástico (esto permite ver tu estado de hidratación)": "urine_color_index",
    "¿Cuentas con algunos de estos instrumentos?": "available_instruments",
    "¿Tienes algún tipo de alimentación \"específica\"?": "specific_diet_type",
    "¿Quién prepara tu comida?": "cooks_for_self",
    "¿Te gusta cocinar?": "likes_cooking",
    "Si tu respuesta fue SI ¿Qué preparaciones realizas?": "cooking_preparations",
    "¿Tienes alergia algún alimento?": "food_allergies",
    "¿Eres intolerante a algún alimento?": "food_intolerances",
    "Si tu respuesta fue si en la anterior pregunta. ¿ A qué tipo de alimento eres intolerante?": "intolerance_details",
    "¿Qué lácteo consumes?": "dairy_consumption",
    "Especifica la marca y tipo de los lácteos que consumes": "dairy_brands",
    "¿Consumes algún suplemento?": "supplements_consumption",
    "Si tu respuesta fue SI ¿Qué tipo de suplemento consumes? Puedes marcas más de una alternativa": "supplement_types",
    "¿Qué cereales NO TE AGRADAN ?": "disliked_cereals",
    "¿Qué tubérculos NO TE AGRADAN?": "disliked_tubers",
    "¿Qué Menestras NO TE AGRADAN ?": "disliked_legumes",
    "¿Qué verduras NO TE AGRADAN ?": "disliked_vegetables",
    "¿Qué frutas NO TE AGRADAN ?": "disliked_fruits",
    "¿Qué carnes o derivados NO TE AGRADAN ?": "disliked_meats",
    "¿Qué grasas NO TE AGRADAN?": "disliked_fats",
    "¿Qué preparaciones no te agradan?": "disliked_preparations",
    "¿Qué alimentos no saludables consumías antes de iniciar tu cambio de hábitos? Puedes seleccionar más de 1 alternativa": "previous_unhealthy_habits",
    "¿A qué hora despiertas?": "wake_up_time",
    "¿ A qué hora duermes?": "sleep_time",
    "¿A qué hora consumes tu desayuno?": "breakfast_time",
    "¿Qué alimentos consumes frecuentemente y/o prefieres en tu desayuno? Detallar la respuesta": "breakfast_details",
    "¿A qué hora consumes tu almuerzo?": "lunch_time",
    "¿Qué alimentos consumes frecuentemente y/o prefieres en tu almuerzo? Detallar la respuesta": "lunch_details",
    "¿A qué hora consumes tu cena?": "dinner_time",
    "¿Qué alimentos consumes frecuentemente y/o prefieres en tu Cena? Detallar la respuesta": "dinner_details",
    "¿Qué alimentos consumes frecuentemente y/o prefieres en tu media mañana o media tarde? Detallar respuesta": "snack_details",
    "Foto de Frente": "front_photo_url",
    "Foto de Costado 1": "side_photo_1_url",
    "Foto de Costado 2": "side_photo_2_url",
    "Foto de Espalda": "back_photo_url",
    "Foto frontal del producto y de la información nutricional (puede ser una sola foto si entran ambos o dos fotos) (Lácteos)": "dairy_photos",
    "Foto frontal del producto y de la información nutricional (puede ser una sola foto si entran ambos o dos fotos) (Suplementos)": "supplement_photos",
    "¿Qué tipo de preparación prefieres? ¿Fáciles o difíciles? ": "prep_preference",
    "¿Qué tipo de preparación prefieres? ¿Dulces o salados? ": "taste_preference"
};
